school :
	@echo "$@"
MPC : school
	@echo "$@"
BiPC : school
	@echo "$@"
JEE : MPC
	@echo "$@"
NEET : BiPC
	@echo "$@"
IIT : JEE
	@echo "$@"
NIT : JEE
	@echo "$@"
AIIMS : NEET
	@echo "$@"
CMC : NEET
	@echo "$@"
Soft.Eng : IIT
	@echo "$@"
MS : IIT
	@echo "$@"
Hard.Eng : NIT
	@echo "$@"
Gynic : AIIMS
	@echo "$@"
ENT : AIIMS
	@echo "$@"
MD : AIIMS
	@echo "$@"
Dentist : CMC
	@echo "$@"
Research.Eng : Soft.Eng MS
	@echo "$@"
IVF.spec : Gynic MD
	@echo "$@"